### PR TITLE
refactor(tests): move to jest

### PR DESCRIPTION
**Pull request by wolfy1339**
Required for #407 as `tap` doesn't seem to like ESModules

### CODE REVIEW

**Comment by gr2m** [comment]
Hm I thought `tap` works well with ESM since v15?
https://github.com/tapjs/node-tap/releases/tag/v15.0.0

But I don't mind the change

**Comment by gr2m** [comment]
I've resolved the conflict. Do you want to finish this up?

**Comment by wolfy1339** [comment]
This isn't strictly necessary, but a nice to have. It would make all octokit JS repos uniform

**Comment by wolfy1339** [comment]
I'm looking into it

**Comment by wolfy1339** [comment]
Hmm... The tests fail, but if I upgrade jest to v27 they pass

**Comment by gr2m** [comment]
any idea why coverage could have dropped? We had 100% before

**Comment by wolfy1339** [comment]
No idea currently.

**Comment by gr2m** [comment]
The `npm test` script did not include the test files in `test/`. A few tests are failing now, would you like to finish this up yourself or shall I?

**Comment by gr2m** [comment]
I forced pushed to resolve the conflicts @wolfy1339

**Comment by wolfy1339** [comment]
Tests are failing due to timeouts

**Review by gr2m — APPROVED** [review]
I think this is good to go now

**Pull request merged**
