### PR TITLE
feat: rewrite in ESModules

### PR DESCRIPTION
**Pull request by wolfy1339**

### CODE REVIEW

**Comment by wolfy1339** [comment]
There's 3 commits that aren't totally related to this PR, that fix deprecation warnings with `tap`
- fix: replace deprecated `t.is` with `t.equal` 2ce8b05
- fix: replace `t.isA` with `t.type` c5bf865 
-  fix: replace `t.deepEqual` with `t.same` 9a5cbbf

Should I split them off?

***

Otherwise, the tests run, but they fail due to mismatches in expected output. I am unsure why that would happen with the switch to ESM.

**Comment by gr2m** [comment]
you had incorrect imports. If the file has

```js
export default temporaryRepository;
export const regex
```

then you cannot access `temporaryRepository.regex`, you have to do

```js
import temporaryRepository, { regex } from '...'
```

**Comment by gr2m** [comment]
Hm I cannot reproduce the failing test locally, can you?

Also `npm run record` is currently failing, I'm looking into that

**Comment by wolfy1339** [comment]
I cannot reproduce the failing test locally with NodeJS v16

**Comment by wolfy1339** [comment]
> Also npm run record is currently failing, I'm looking into that

It's because in ESM you can't implicitly import the `index.js` located in a folder, you have to import it explicitly. Which I did account for. Must've missed these ones
I found another case of it in `bin/remove-temporary-repositories.js`

**Comment by gr2m** [comment]
depends on https://github.com/octokit/fixtures/pull/411

**Comment by wolfy1339** [comment]
Alright, only 3 failing tests remain.

There's a problem with `bin/record.js --update`, it's removing data from fixtures.

**Comment by gr2m** [comment]
We are down the the normalize test failing because of how the entity IDs are calculated. I tried to figure out where the diff is coming from but I don't know. I think it might be that the keys in an object are sorted differently, because IDs from the recorded fixtures are mapped to the made-up IDs starting at 1000 instead. Maybe you have an idea what might be going on? It's odd because the record tests all pass, but when running the normalization test in isolation it finds a diff

**Comment by wolfy1339** [comment]
Pinging @octokit/js-community
Can of you look at this to help figure out why the IDs are differing between the CommonJS version and this PR?

**Comment by wolfy1339** [comment]
The problem seems to stem from using `Promises`.
Making the test use a for-of loop instead of `Promise.all` makes it pass. (also changing the `Promise.all` in `lib/normalize/index.js`)

**Comment by wolfy1339** [comment]
With this patch the test works normally.
```diff
diff --git a/lib/normalize/index.js b/lib/normalize/index.js
index 129e5f8..a7c879c 100644
--- a/lib/normalize/index.js
+++ b/lib/normalize/index.js
@@ -83,17 +83,15 @@ async function normalize(scenarioState, fixture) {
   const responses = Array.isArray(fixture.response)
     ? fixture.response
     : [fixture.response];
-  await Promise.all(
-    responses.map(async (response) => {
-      normalizeCommon(response);
-      const entityName = toEntityName(response, fixture);
-      if (entityName) {
-        await (
-          await import(`./${entityName}.js`)
-        ).default(scenarioState, response, fixture);
-      }
-    })
-  );
+  for (let response of responses) {
+    normalizeCommon(response);
+    const entityName = toEntityName(response, fixture);
+    if (entityName) {
+      await (
+        await import(`./${entityName}.js`)
+      ).default(scenarioState, response, fixture);
+    }
+  }
 
   // update content length
   if (/^application\/json/.test(fixture.headers["content-type"])) {
diff --git a/test/integration/normalize.test.js b/test/integration/normalize.test.js
index 9166649..accbe2f 100644
--- a/test/integration/normalize.test.js
+++ b/test/integration/normalize.test.js
@@ -19,9 +19,11 @@ glob
         commitSha: {},
         ids: {},
       };
-      const actual = await Promise.all(
-        raw.filter(isntIgnored).map(normalize.bind(null, scenarioState))
-      );
+      const actual = [];
+      for (let item of raw.filter(isntIgnored)) {
+        let result = await normalize.bind(null, scenarioState)(item);
+        actual.push(result);
+      }
       expect(actual).toEqual(expected);
     });
   });
```

All thanks to my friend @iovoid who diagnosed this and found the issue

**Comment by gr2m** [comment]
sounds great 👍🏼 thanks @io4! Can you push the change?

**Review by gr2m — APPROVED** [review]
Great work 👏🏼

**Pull request merged**
