### PR TITLE
README: updated record scenario instructions

### PR DESCRIPTION
**Pull request by gr2m**
### [Preview](https://github.com/octokit/fixtures/blob/readme-record-instructions/README.md#updating-fixtures) 👀

### CODE REVIEW

**Comment by jarrodldavis** [comment]
I think this could be worded a bit better to clearly indicate the `scenarios` -> `host` -> `scenario name` folder hierarchy:
https://github.com/octokit/fixtures/blob/397effdf4c610f5ad8dac26ce1a255fb496a4b67/README.md#L177-L178

For a second I was confused and thought this meant to create a `record.js` file directly in the `api.github.com` folder, but looking at existing folder hierarchy you have clarifies this instruction.

**Comment by gr2m** [comment]
how about this

> create a new folder in the [scenarios/<host>/ folder](scenarios/) that matches the host
   name you send requests to. In that folder, create a [`record.js`](#record-js-file) file.

Maybe I should explain it all with an example as I keep referring to the scenario name ...

**Comment by jarrodldavis** [comment]
Yeah, I think a concrete example (like the `Get root` scenario used in steps 2 and 3) would help.

**Comment by jarrodldavis** [comment]
Also I don't see the difference between the wording in your comment and the existing README except for double slashes.

**Comment by gr2m** [comment]
> Also I don't see the difference between the wording in your comment and the existing README except for double slashes.

fixed

**Comment by jarrodldavis** [comment]
Okay I think that works. 👍

**Comment by jarrodldavis** [comment]
If you update step 1 to have a `<host>` placeholder though, I think the other steps should have a placeholder as well for consistency.

**Comment by gr2m** [comment]
I’ve changed it to use an example

**Comment by jarrodldavis** [comment]
Looks good

**Pull request merged**
